<?php
/**
 * @var $block \Venbhas\Blog\Block\Frontend\Article\Toolbar
 */
?>
<?php if ($block->getCollection() && $block->getCollection()->getSize()): ?>
    <?php
    $widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($block->getWidgetOptionsJson());
    $widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['productListToolbarForm']);
    ?>
    <div class="toolbar toolbar-products" data-mage-init='{"productListToolbarForm":<?= /* @noEscape */ $widgetOptions ?>}'>
        <?php if ($block->getIsBottom()): ?>
            <?= $block->getPagerHtml() ?>
            <?= $block->fetchView($block->getTemplateFile('Venbhas_Blog::article/list/toolbar/limiter.phtml')) ?>
        <?php else: ?>
            <?= $block->fetchView($block->getTemplateFile('Venbhas_Blog::article/list/toolbar/amount.phtml')) ?>
            <?php if ($block->isExpanded()): ?>
                <?= $block->fetchView($block->getTemplateFile('Venbhas_Blog::article/list/toolbar/sorter.phtml')) ?>
            <?php endif ?>
        <?php endif ?>
    </div>
<?php endif ?>
