<?php
/**
 * @var $block \Venbhas\Blog\Block\Frontend\Category\ListCategory
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\Locale\LocaleFormatter $localeFormatter
 */
$categories = $block->getCategoryCollection();
$count = is_array($categories) ? count($categories) : $categories->count();
?>
<?php if ($count): ?>
    <div class="block filter">
        <div class="block-title filter-title">
            <strong><?= $escaper->escapeHtml(__('Shop By')) ?></strong>
        </div>
        <div class="block-content filter-content">
            <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle">
                <?= $escaper->escapeHtml(__('Shopping Options')) ?>
            </strong>
            <dl class="filter-options" id="narrow-by-list">
                <dt role="heading" aria-level="3" class="filter-options-title">
                    <?= $escaper->escapeHtml(__('Category')) ?>
                </dt>
                <dd class="filter-options-content">
                    <ol class="items">
                        <?php foreach ($categories as $category): ?>
                            <?php
                            $categoryUrl = $block->getCategoryUrl($category);
                            $articleCount = $block->getArticleCount($category);
                            ?>
                            <li class="item">
                                <a href="<?= $escaper->escapeUrl($categoryUrl) ?>"
                                    <?php if ($block->isCategoryActive($category)): ?>
                                        class="current"
                                    <?php endif; ?>
                                ><?= $escaper->escapeHtml($category->getName()) ?><span class="count">
                                    <?= $escaper->escapeHtml($localeFormatter->formatNumber($articleCount)) ?><span
                                        class="filter-count-label"><?php
                                        if ($articleCount === 1): ?>
                                            <?= $escaper->escapeHtml(__('item')) ?><?php
                                        else: ?>
                                            <?= $escaper->escapeHtml(__('items')) ?><?php
                                        endif; ?></span></span></a>
                            </li>
                        <?php endforeach; ?>
                    </ol>
                </dd>
            </dl>
        </div>
    </div>
<?php endif; ?>
