<?php
/**
 * @var $block \Venbhas\Article\Block\Frontend\Article\View
 * @var \Magento\Framework\Escaper $escaper
 */
$article = $block->getArticle();
if (!$article):
    return;
endif;
?>
<div class="venbhas-article-view">
    <h1 class="article-title"><?= $escaper->escapeHtml($article->getTitle()) ?></h1>
    <div class="article-content">
        <?= /* @noEscape */ $article->getDescription() ?>
    </div>
</div>
