<?php
/**
 * @var $block \Venbhas\Blog\Block\Frontend\Article\Toolbar
 * @var string $pager_html
 */
?>
<?php
$widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($block->getWidgetOptionsJson());
$widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['productListToolbarForm']);
?>
<div class="toolbar toolbar-products" data-mage-init='{"productListToolbarForm":<?= /* @noEscape */ $widgetOptions ?>}'>
    <?= /* @noEscape */ ($pager_html ?? '') ?>
    <?= $block->fetchView($block->getTemplateFile('Venbhas_Blog::article/list/toolbar/limiter.phtml')) ?>
</div>
